=== dfsoeten/webs4/planning.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/planning" xmlns:tns="http://www.example.org/planning" elementFormDefault="qualified">


    <element name="planning" type="tns:planning"></element>
    
    <complexType name="planning">
    	<sequence>
    		<element name="periode" type="tns:periode" maxOccurs="4"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>
    

    <complexType name="periode">
    	<sequence>
    		<element name="week" type="tns:week" maxOccurs="7"
    			minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="nr" type="int"></attribute>
    </complexType>
    
    <complexType name="week">
    	<sequence>
    		<element name="afspraak" type="tns:afspraak"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="nr" type="int"></attribute>
    </complexType>
    
    <complexType name="afspraak">
    	<sequence>
    		<element name="title" type="string"></element>
    		<element name="dag" type="string"></element>
    		<element name="datum" type="dateTime"></element>
    		<element name="locatie" type="tns:locatie"></element>
    		<element name="persoon" type="tns:persoon" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="locatie">
    	<sequence>
    		<element name="gebouw" type="string"></element>
    		<element name="lokaal" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="persoon">
    	<sequence>
    		<element name="naam" type="string"></element>
    		<element name="email" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== dfsoeten/webs4/planning.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="jsonConverter.xsl" type="application/xml"?>
<tns:planning xmlns:tns="http://www.example.org/planning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/planning planning.xsd ">
  <tns:periode nr="1">
    <tns:week nr="1">
      <tns:afspraak>
        <tns:title>WEBS4 Tentamen</tns:title>
        <tns:dag>Woensdag</tns:dag>
        <tns:datum>2019-06-12T11:45:00</tns:datum>
        <tns:locatie>
          <tns:gebouw>tns:gebouw</tns:gebouw>
          <tns:lokaal>tns:lokaal</tns:lokaal>
        </tns:locatie>
        <tns:persoon>
          <tns:naam>tns:naam</tns:naam>
          <tns:email>tns:email</tns:email>
        </tns:persoon>
      </tns:afspraak>
    </tns:week>
    <tns:week nr="2">
      <tns:afspraak>
        <tns:title>tns:title</tns:title>
        <tns:dag>tns:dag</tns:dag>
        <tns:datum>2001-12-31T12:00:00</tns:datum>
        <tns:locatie>
          <tns:gebouw>tns:gebouw</tns:gebouw>
          <tns:lokaal>tns:lokaal</tns:lokaal>
        </tns:locatie>
        <tns:persoon>
          <tns:naam>tns:naam</tns:naam>
          <tns:email>tns:email</tns:email>
        </tns:persoon>
      </tns:afspraak>
    </tns:week>
  </tns:periode>
  <tns:periode nr="2">
    <tns:week nr="1">
      <tns:afspraak>
        <tns:title>tns:title</tns:title>
        <tns:dag>tns:dag</tns:dag>
        <tns:datum>2001-12-31T12:00:00</tns:datum>
        <tns:locatie>
          <tns:gebouw>tns:gebouw</tns:gebouw>
          <tns:lokaal>tns:lokaal</tns:lokaal>
        </tns:locatie>
        <tns:persoon>
          <tns:naam>tns:naam</tns:naam>
          <tns:email>tns:email</tns:email>
        </tns:persoon>
      </tns:afspraak>
    </tns:week>
  </tns:periode>
</tns:planning>
